### ISSUE TITLE
wasm_exec.js  throw new Error("Go program has already exited");

### ISSUE THREAD

**Issue by jsrj78** [norunners/vue#40] opened 2019-08-19 05:39 UTC
Hi  Norunners

When I follow your guidelines and run “wasmgo serve” in example dir(06-two-way-data-binding）.Everything is very better.

But When I copy code to my project and run .When I change input value, the demo raise error :"Go program has already exited"

My code list:

main.go

const tmpl = `

  <p>{{ Message }}</p>
  <input v-model="Message">

`

func main(){

vue.New(
		vue.El("#app"),
		vue.Template(tmpl),
		vue.Data(Data{Message: "Hello WebAssembly!"}),
	)

select {}

}

GOOS=js GOARCH=wasm go build -o main.wasm
--------------------------
index.html

<html>
	<head>
		<meta charset="utf-8">
		<script src="wasm_exec.js"></script>
		<script>
			const go = new Go();
			WebAssembly.instantiateStreaming(fetch("main.wasm"), go.importObject).then((result) => {
				go.run(result.instance);
			});
		</script>
	</head>
	<body>
        <div id="app">
        </div>
    </body>
</html>

 goexec 'http.ListenAndServe(":8080", http.FileServer(http.Dir(".")))'

------------------------------------------

my go version:

go version go1.12.7 darwin/amd64

I am run code on MacOS 64

Please you to help me.

**Comment by norunners** [comment] 2019-09-06 17:18
Hello, sorry for the delayed response. I'm not able to reproduce this locally. The error appears as though the select is not honored. It's possible that the Go version does not match the Go specific wasm resource versions but it's just a guess.

Also, can you include the full `main.go` and `index.html` source, I'm not seeing the element with the id of `app`.

**Comment by norunners** [comment] 2020-03-29 02:23
Resolving this due to age. Feel free to open a new issue.

**Closed as completed by norunners** 2020-03-29 02:23 UTC

**Comment by eric-burel** [comment] 2022-09-21 16:03
![image](https://user-images.githubusercontent.com/7983005/191554135-3b61e2f3-4c36-4b91-9408-14ad92a138c1.png)

For lost Googlers, it seems that this issue happens when your Go main function does indeed exit. A solution is to add `select {}` at the end of your main call, which will wait forever before leaving (an infinite loop WON'T work however). Found the idea in this tutorial: https://marianogappa.github.io/software/2020/04/01/webassembly-tinygo-cheesse/

The code in this issue should probably have worked in the first place because it contains this `select {}` so it probably failed for another reason. An alternative syntax seems to be `<-make(chan bool)`
